import type { Metadata } from 'next';

import '../styles';
import { Providers } from '@/app/providers';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="ru">
            <body className={`antialiased`}>
                <Providers>{children}</Providers>
            </body>
        </html>
    );
}
